Projects default to 6 accounts. Add ft/nft contract templates to acc 5/6
onflow/flow-playground pull request #134
Opened 2021-03-17 13:48 UTC by timongll

Closes: #44

Alot of projects require more than 5 accounts and 5 contracts (eg. nbats requires 6+) Added 1 more account to default and also added fungible token contract template to account 5 and non-fungible token contract template to account 6 so that people would not need to copy paste these standard contracts

2021-03-18 01:47 UTC, 10thfloor commented
Nice. Thanks for the issue :) Would be cool if we could run NBA TopShot in the Playground, but I think that will have to wait until the playground supports multi-contract per account, like the real network.

We actually have an issue for help out with the whole copy/paste thing: 
https://github.com/onflow/flow-playground/issues/44

2021-03-18 01:53 UTC, timongll commented
@10thfloor Cool! will try to make the dropdown

2021-03-18 01:53 UTC, 10thfloor commented
> @10thfloor Cool! will try to make the dropdown

Awesome cc @MaxStalker

2021-03-18 01:56 UTC, 10thfloor requested changes
See my comments in the PR thread above ☝🏼

2021-05-18 16:19 UTC, 10thfloor commented
Closing because stale.

2021-05-18 16:19 UTC, closed without merging