Language Server Refactor
onflow/flow-playground pull request #222
Opened 2022-02-04 19:55 UTC by MaxStalker

Closes: #206 

## Description
This shall fix delayed updates to deployed contracts. Now it will properly update diagnostics about missing/non-existing fields and contracts.

❗ Attention - This is not yet ready to be merged ❗ 
[ ] - Provide working solution that will fix the issue
[ ] - Check that code refreshes properly and does not affects language client
[ ] - Refactor code and remove all unnecessary console logs and `spaghetti` code 😅

2022-02-07 14:15 UTC, MaxStalker commented
@10thfloor can you take a look? :bow:

2022-02-07 16:43 UTC, 10thfloor requested changes

2022-02-07 16:43 UTC, 10thfloor commented on src/components/Arguments/index.tsx
> +          // await updateAccountDeployedCode();
Dead code? Can we remove?

2022-02-07 16:43 UTC, 10thfloor commented on src/containers/Editor/components.tsx
> +  })*/
More dead code.

2022-02-07 16:44 UTC, 10thfloor commented
@MaxStalker Looks good. I tested and it is working. Some minor cleanup and we can merge this.

2022-02-15 13:27 UTC, MaxStalker commented
![Screenshot from 2022-02-15 16-25-36](https://user-images.githubusercontent.com/3136647/154071242-b678c404-588b-4eb5-9c1f-e6d458034e5d.png)

#204 issue is not the issue anymore, thanks to new language server package.

2022-02-15 18:05 UTC, 10thfloor approved these changes

2022-02-15 18:05 UTC, merged