Regexp issues, during signers extraction
onflow/flow-playground pull request #224
Opened 2022-02-08 14:02 UTC by MaxStalker

Closes: #212 

Potential improvement for language server as we should read this data from it and not parsing Cadence code on front-end.

2022-02-10 22:21 UTC, 10thfloor requested changes

2022-02-10 22:21 UTC, 10thfloor commented on src/util/parser.ts
> +    console.log({ noComments })
```suggestion
```

2022-02-10 22:31 UTC, MaxStalker commented on src/util/parser.ts
> +    console.log({ noComments })
Addressed!

2022-02-15 18:08 UTC, 10thfloor approved these changes

2022-02-15 18:10 UTC, merged